version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  node14:
    docker:
      - image: cimg/node:lts  # Usa la última versión LTS de Node.js
    resource_class: medium

commands:
  nodesetup:
    description: "Configuración del proyecto: Checkout y dependencias"
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          app-dir: ~/project/

jobs:
  install_dependencies:
    executor: node14
    steps:
      - nodesetup

  lint:
    executor: node14
    steps:
      - nodesetup
      - run:
          name: Linting del Código
          command: npm run lint

  test_unit:
    executor: node14
    parallelism: 2  # Ejecuta pruebas unitarias en paralelo en dos contenedores
    steps:
      - nodesetup
      - run:
          name: Pruebas Unitarias
          command: npm run test:unit

  test_integration:
    executor: node14
    steps:
      - nodesetup
      - run:
          name: Pruebas de Integración
          command: npm run test:integration

  notify_success:
    executor: node14
    steps:
      - run:
          name: Notificar Éxito
          command: |
            echo "Pipeline completado con éxito"
            curl -X POST -H "Content-Type: application/json" \
            -d '{"text": "Pipeline completado exitosamente en el workflow: '"${CIRCLE_WORKFLOW_ID}"'"}' \
            https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK

  notify_failure:
    executor: node14
    steps:
      - run:
          name: Notificar Error
          command: |
            echo "El pipeline falló"
            curl -X POST -H "Content-Type: application/json" \
            -d '{"text": "El pipeline falló en el workflow: '"${CIRCLE_WORKFLOW_ID}"'"}' \
            https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK

workflows:
  version: 2

  # Primer Workflow: Pipeline Principal
  main_pipeline:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test_unit:
          requires:
            - lint
      - test_integration:
          requires:
            - test_unit
      - notify_success:
          requires:
            - test_integration

  # Segundo Workflow: Notificación de Error
  notify_workflow:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test_unit:
          requires:
            - lint
      - test_integration:
          requires:
            - test_unit
      - notify_failure:
          requires:
            - test_integration
