version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  node14:
    docker:
      - image: 'cimg/node:14.17.0 '
    resource_class: medium

commands:
  nodesetup:
    description: "Setup del proyecto: Checkout y dependencias"
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          app-dir: ~/project/

jobs:
  install_dependencies:
    executor: node14
    steps:
      - nodesetup

  lint:
    executor: node14
    steps:
      - nodesetup
      - run:
          name: Linting del Código
          command: npm run lint

  test_unit:
    executor: node14
    parallelism: 2
    steps:
      - nodesetup
      - run:
          name: Pruebas Unitarias
          command: npm run test:unit

  test_integration:
    executor: node14
    steps:
      - nodesetup
      - run:
          name: Pruebas de Integración
          command: npm run test:integration

  notify:
    executor: node14
    steps:
      - run:
          name: Notificar Éxito
          command: |
            echo "Notificación: El pipeline se completó con éxito"
            curl -X POST -H "Content-Type: application/json" \
            -d '{"text": "Pipeline completado exitosamente en workflow: '"${CIRCLE_WORKFLOW_ID}"'"}' \
            https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK

workflows:
  version: 2

  main_pipeline:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test_unit:
          requires:
            - lint
      - test_integration:
          requires:
            - test_unit
      - notify:
          requires:
            - test_integration
